{
 "title": "Podinfo - Golden Signals",
 "panels": [
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"demo\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "podinfo:error_ratio:rate5m" }
   ]
  },
  {
   "title": "p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"demo\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU by pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"demo\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod restarts (15m increase)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"demo\"}[15m])"
    }
   ]
  }
 ]
}